### PR TITLE
mbl-cloud-client: Update mbed-cloud-client to version 4.1.0

### PR DESCRIPTION
**Pull request by esajaa**
Also update the pal-platform to 4.1.0

### CODE REVIEW

**Comment by jonathanhaigh-arm** [comment]
meta-mbl branch that points to https://github.com/ARMmbed/mbl-core/pull/265/commits/4335ad61f0ebe7a980a98c93198720f83c142d7b: https://github.com/ARMmbed/meta-mbl/tree/jh-update_client_to_410

mbl-manifest branch that points to https://github.com/ARMmbed/meta-mbl/tree/jh-update_client_to_410:  https://github.com/ARMmbed/mbl-manifest/tree/jh-update_client_to_410

Jenkins build using https://github.com/ARMmbed/mbl-manifest/tree/jh-update_client_to_410: http://jenkins.mbed-linux.arm.com/view/jh/job/jh-test/212/

**Comment by jonathanhaigh-arm** [comment]
The Jenkins jobs are failing with:
```
[2019-12-03T14:48:02.500Z] NOTE: recipe mbl-cloud-client-1.0-r0: task do_patch: Started
[2019-12-03T14:48:03.084Z] ERROR: mbl-cloud-client-1.0-r0 do_patch: Command Error: 'quilt --quiltrc /mnt/workspace/jh-test/machine-imx7s-warp-mbl/mbl-manifest/build-mbl-development/tmp/work/armv7vet2hf-neon-oe-linux-gnueabi/mbl-cloud-client/1.0-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
[2019-12-03T14:48:03.084Z] Applying patch arg_too_long_fix_1.patch
[2019-12-03T14:48:03.084Z] patching file cloud-services/mbl-cloud-client/pal-platform/Middleware/mbedtls/mbedtls.cmake
[2019-12-03T14:48:03.084Z] Hunk #1 FAILED at 19.
[2019-12-03T14:48:03.084Z] 1 out of 1 hunk FAILED -- rejects in file cloud-services/mbl-cloud-client/pal-platform/Middleware/mbedtls/mbedtls.cmake
[2019-12-03T14:48:03.084Z] Patch arg_too_long_fix_1.patch does not apply (enforce with -f)
[2019-12-03T14:48:03.084Z] ERROR: Logfile of failure stored in: /mnt/workspace/jh-test/machine-imx7s-warp-mbl/mbl-manifest/build-mbl-development/tmp/work/armv7vet2hf-neon-oe-linux-gnueabi/mbl-cloud-client/1.0-r0/temp/log.do_patch.654
[2019-12-03T14:48:03.084Z] NOTE: recipe mbl-cloud-client-1.0-r0: task do_patch: Failed
[2019-12-03T14:48:03.084Z] ERROR: Task (/mnt/workspace/jh-test/machine-imx7s-warp-mbl/mbl-manifest/build-mbl-development/conf/../../layers/meta-mbl/meta-mbl-apps/recipes-connectivity/mbl-cloud-client/mbl-cloud-client.bb:do_patch) failed with exit code '1'
```
At least one of our mbed-cloud-client patches now fails to apply. Let me look into it...

**Comment by jonathanhaigh-arm** [comment]
> Let me look into it...

I don't think I can provide a really quick fix. Looking at some of the patches we've got, I'm surprised we haven't upstreamed them to mbed-cloud-client (or it's related libraries) or otherwise eliminated them. We should probably think what to do about each one and try to get some changes into mbed-cloud-client.

I've raised https://jira.arm.com/browse/IOTMBL-2665 to deal with this.

**Comment by diego-sueiro** [comment]
@jonathanhaigh-arm, can you please review this PR and merge it?
The PR https://github.com/ARMmbed/meta-mbl/pull/825 is ready for approval and merge as well.

**Comment by jonathanhaigh-arm** [comment]
@diego-sueiro, see my comments at ARMmbed/meta-mbl#825 .

**Comment by diego-sueiro** [comment]
@jonathanhaigh-arm, any additional comments on this PR?

**Pull request merged**
